# -*- coding: utf-8 -*-
"""Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16m0UdJ7hOQOkWqlklesR8vXtjxct1AoW
"""

import pandas as pd
data = pd.read_csv("/content/logistic_regression_dataset.csv")
data.head()

data_Gender = pd.get_dummies(data['Gender'])
df = data.drop(['Gender'], axis = 1)
data_new = pd.concat([df, data_Gender], axis = 1)
print(data_new)

#Problem 2(A)
from sklearn.model_selection import train_test_split
# split the dataset into train and test sets
#X = data.iloc[:,[1,2]]
#y = data.iloc[:,3]
trainingSet, testSet = train_test_split(data_new, test_size=0.2)
train_data_new = trainingSet
test_data_new = testSet
X_train = train_data_new[['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Female', 'Male']]
y_train = train_data_new['Purchased']
X_test = test_data_new[['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Female', 'Male']]
y_test = test_data_new['Purchased']

print(f"Train labels:{y_train.shape[0]}")
print(f"Test labels:{y_test.shape[0]}")

X_train

#2(B)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
y_pred

#2(C)
from sklearn import metrics
from sklearn.metrics import confusion_matrix  
cnf_mat= confusion_matrix(y_test, y_pred)  
print("Accuracy = ", metrics.accuracy_score(y_test,y_pred))
print("Confusion matix:", cnf_mat)

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize = (9,6))
sns.heatmap(cnf_mat, annot = True)
plt.title("Confusion Matrix")
plt.xlabel("Predicted(y_pred)")
plt.ylabel("True(y_test)")
plt.show()

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test, y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))